version: 2.1

orbs:
  node: circleci/node@4.1

  jobs:
    lint:
      steps:
        - checkout
        - node/install:
            node-version: latest
        - run: npm ci && npm run lint

workflows:
  build:
    jobs:
      - lint:
          version: '15.1'
