version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-npm
      - node/install-packages
      - run: npm test

workflows:
  test-lint:
    jobs:
      - test
