version: 2.1

orbs:
  node: circleci/node@5.0.0

jobs:
  test:
    docker:
      - image: cimg/node:16.8.0-browsers
    steps:
      - checkout
      - node/install-packages
      - run: npm test
      - run: npm run lint
    resource_class: large
  package:
    docker:
      - image: cimg/node:16.8.0-browsers
    steps:
      - checkout
      - node/install-packages
      - run: npm run vsix
      - run: mkdir /tmp/artifacts && mv local-ci*.vsix /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
    resource_class: large

workflows:
  test-lint:
    jobs:
      - test
      - package
