version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  lint:
    executor: node/default
    steps:
      - checkout
      - node/install-npm
      - node/install-packages
      - run: npm run lint

workflows:
  lint-test:
    jobs:
      - lint
