version: 2.1

orbs:
  node: circleci/node@4.1
  browser-tools: circleci/browser-tools@1.1.0

executors:
  node:
    docker:
      - image: cimg/node:16.8.0-browsers

jobs:
  test:
    executor:
      name: node
    steps:
      - browser-tools/install-browser-tools
      - node/install-npm
      - checkout
      - node/install-packages
      - run: npm test

workflows:
  test-lint:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
