version: 2.1

orbs:
  node: circleci/node@5.0.0
  browser-tools: circleci/browser-tools@1.1.0

jobs:
  test:
    docker:
      - image: cimg/node:16.8.0-browsers
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - node/install-npm
      - node/install-packages
      - run: npm test

workflows:
  test-lint:
    jobs:
      - test
