version: 2.1

orbs:
  node: circleci/node@4.1
  browser-tools: circleci/browser-tools@1.1.0

executors:
  node:
    docker:
      - image: cimg/node:16.8.0-browsers

jobs:
  test:
    executor:
      name: node
    steps:
      - browser-tools/install-browser-tools
      - node/install-npm
      - checkout
      - node/install-packages
      - run: npm test
  publish:
    executor:
      name: node
    steps:
      - browser-tools/install-browser-tools
      - node/install-npm
      - checkout
      - node/install-packages
      - run:
          name: "Deploy plugin to marketplace"
          command: npm run deploy

workflows:
  test-publish:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - test
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
