version: 2.1

orbs:
  node: circleci/node@5.0.0
  browser-tools: circleci/browser-tools@1.1.0

jobs:
  test:
    docker:
      - image: cimg/node:16.8.0-browsers
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - node/install-packages
      - run: npm test
  build:
    docker:
      - image: cimg/node:16.8.0-browsers
    steps:
      - checkout
      - node/install-packages
      - run: npm run vsix
      - run: mkdir /tmp/artifacts && mv local-ci*.vsix /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  test-lint:
    jobs:
      - test
      - build
